install.packages('tidyverse')
install.packages('ggplot2')
install.packages('rmarkdown')
install.packages('shiny')
install.packages('reticulate')
install.packages('devtools')
install.pacakges('keras')
